[package]
name = "rua_proto"
version = "0.1.0"
authors = ["fjhg19930505 <ziyoulu1993@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-serialize = "0.3.24"
